#!/bin/sh

# sudo not required for some system commands
for command in openvpn mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkdir="mkdir -pv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lAF1" \
	dir="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

# Enable the use of alias after the sudo command
alias sudo="sudo "

# force zsh to show the complete history
alias history="history 0"

# Better lf
alias lf="lfrun"

# Always use neovim and add session support
function nvim() {
  if test $# -gt 0; then
    env nvim "$@"
  elif test -f Session.vim; then
    env nvim -S
  else
    env nvim -c Obsession
  fi
}
alias vim="nvim" vimdiff="nvim -d"

# Launch VPN quickly
alias tryhackme="sudo openvpn --config $HOME/documents/ovpn_configs/tryhackme.ovpn"
alias prolabs="sudo openvpn --config $HOME/documents/ovpn_configs/pro_labs_Xenorf.ovpn"
alias playground="sudo openvpn --config $HOME/documents/ovpn_configs/pg.ovpn"
alias offsec="sudo openvpn --config $HOME/documents/ovpn_configs/universal.ovpn"

# Favorite directories
alias dl="cd $HOME/downloads"
alias doc="cd $HOME/documents"
alias logs="cd $HOME/logs"
alias src="cd $HOME/.local/src"
alias config="cd $XDG_CONFIG_HOME"
alias cache="cd $XDG_CACHE_HOME"
alias bin="cd $HOME/.local/bin"
alias certificates="cd /usr/local/share/ca-certificates"

alias myip="curl ifconfig.io"
alias startx="startx 2>$HOME/logs/startx.log"
alias chrome="chromium"
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
