#!/bin/sh

# Profile file, runs on login. Environmental variables are set here.

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="chromium"

# ~/ Clean-up:
# XDG_RUNTIME_DIR is already set
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export GRIM_DEFAULT_DIR="$HOME/documents/screenshots"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_STATE_HOME/history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"
# export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
# export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
# export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
# export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
# export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
#export GNUPGHOME="$XDG_DATA_HOME/gnupg"
# export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
# export KODI_DATA="$XDG_DATA_HOME/kodi"
# export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
# export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
# export CARGO_HOME="$XDG_DATA_HOME/cargo"
# export GOPATH="$XDG_DATA_HOME/go"
# export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
# export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
# export UNISON="$XDG_DATA_HOME/unison"
# export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
# export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
# export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"

# Other program settings:
# export DICS="/usr/share/stardict/dic/"
# export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
# export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
# export LESS="R"
# export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
# export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
# export LESS_TERMCAP_me="$(printf '%b' '[0m')"
# export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
# export LESS_TERMCAP_se="$(printf '%b' '[0m')"
# export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
# export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
# export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
# export QT_QPA_PLATFORMTHEME="gtk2"        # Have QT use gtk2 theme.
# export MOZ_USE_XINPUT2=1                  # Mozilla smooth scrolling/touchpads.
# export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
# export _JAVA_AWT_WM_NONREPARENTING=1      # Fix for Java applications in dwm

# [ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1
(cat "$XDG_CACHE_HOME/wal/sequences" &)
. "$XDG_CACHE_HOME/wal/colors-tty.sh"

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Hyprland >/dev/null 2>&1 && exec Hyprland > /dev/null 2>&1
